/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xia_myled_myJNI */

#ifndef _Included_com_example_xia_myled_myJNI
#define _Included_com_example_xia_myled_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xia_myled_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xia_myled_myJNI_sayHello
  (JNIEnv *env, jclass jobj)
  {
      return (*env)->NewStringUTF(env, "JNI hahahahha");
  }

#ifdef __cplusplus
}
#endif
#endif
